# Generated by Django 4.2 on 2023-04-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='phone',
            field=models.CharField(blank=True, default=False, max_length=15, verbose_name='Phone'),
        ),
    ]
